import { StyleSheet } from 'react-native';
import { colors, spacing, fontSizes, fontWeights, radii } from '@/theme/tokens';

export const friendsRankingStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.textPrimary,
    padding: spacing.s18,
    gap: spacing.s14,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.s12,
  },
  headerCopy: {
    flex: 1,
    gap: spacing.sm,
  },
  title: {
    color: colors.white,
    fontSize: fontSizes.summaryValue,
    fontWeight: fontWeights.extraBold,
    includeFontPadding: false,
  },
  modeSwitch: {
    flexDirection: 'row',
    backgroundColor: colors.darkMuted,
    borderRadius: radii.md,
    padding: spacing.sm,
    gap: spacing.lg,
    borderWidth: 1,
    borderColor: colors.darkSoft,
  },
  modeButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: spacing.s10,
    alignItems: 'center',
  },
  modeButtonActive: {
    backgroundColor: colors.darkSoft,
  },
  modeButtonText: {
    color: colors.textTertiary,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.bold,
    includeFontPadding: false,
  },
  modeButtonTextActive: {
    color: colors.white,
  },
  countBadge: {
    backgroundColor: colors.darkMuted,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.darkSoft,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.xxl,
  },
  countBadgeText: {
    color: colors.white,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.bold,
    includeFontPadding: false,
  },
  summaryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkMuted,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.darkSoft,
    paddingHorizontal: spacing.s16,
    paddingVertical: spacing.s14,
  },
  summaryItem: {
    flex: 1,
    gap: spacing.xs,
  },
  summaryDivider: {
    width: 1,
    height: 26,
    backgroundColor: colors.darkSoft,
    marginHorizontal: spacing.s12,
  },
  summaryLabel: {
    color: colors.textTertiary,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.bold,
    includeFontPadding: false,
  },
  summaryValue: {
    color: colors.white,
    fontSize: fontSizes.metric,
    fontWeight: fontWeights.extraBold,
    includeFontPadding: false,
  },
  rankList: {
    gap: spacing.s10,
  },
  rankCard: {
    backgroundColor: colors.darkMuted,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.darkSoft,
    paddingHorizontal: spacing.s16,
    paddingVertical: 15,
  },
  myCard: {
    borderColor: colors.indigoAccent,
    backgroundColor: colors.navyCard,
  },
  rankRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s10,
  },
  rankBadge: {
    minWidth: 52,
    borderRadius: radii.pill,
    backgroundColor: colors.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s10,
  },
  rankBadgeText: {
    color: colors.white,
    fontSize: fontSizes.md,
    fontWeight: fontWeights.extraBold,
    includeFontPadding: false,
  },
  runnerMeta: {
    flex: 1,
    minWidth: 0,
    gap: spacing.sm,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    minWidth: 0,
  },
  runnerName: {
    color: colors.white,
    flexShrink: 1,
    fontSize: fontSizes.button,
    fontWeight: fontWeights.extraBold,
    includeFontPadding: false,
  },
  selfBadge: {
    backgroundColor: colors.brandLighter,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xs,
  },
  selfBadgeText: {
    color: colors.textPrimary,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.extraBold,
    includeFontPadding: false,
  },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.successInk,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.sm,
  },
  livePillDot: {
    width: 7,
    height: 7,
    borderRadius: radii.pill,
    backgroundColor: colors.successBright,
  },
  livePillText: {
    color: colors.successSoft,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.extraBold,
    includeFontPadding: false,
  },
  metricInline: {
    width: 72,
    alignItems: 'flex-end',
  },
  metricInlineValue: {
    color: colors.white,
    fontSize: fontSizes.rank,
    fontWeight: fontWeights.extraBold,
    includeFontPadding: false,
  },
});
