import { StyleSheet } from 'react-native';
import { colors } from '@/theme/tokens';

export const friendsRankingStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.textPrimary,
    padding: 18,
    gap: 14,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  headerCopy: {
    flex: 1,
    gap: 4,
  },
  title: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '800',
    includeFontPadding: false,
  },
  subtitle: {
    color: colors.border,
    lineHeight: 20,
    includeFontPadding: false,
  },
  modeSwitch: {
    flexDirection: 'row',
    backgroundColor: colors.darkMuted,
    borderRadius: 16,
    padding: 4,
    gap: 6,
    borderWidth: 1,
    borderColor: colors.darkSoft,
  },
  modeButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  modeButtonActive: {
    backgroundColor: colors.darkSoft,
  },
  modeButtonText: {
    color: colors.textTertiary,
    fontSize: 12,
    fontWeight: '700',
    includeFontPadding: false,
  },
  modeButtonTextActive: {
    color: colors.white,
  },
  countBadge: {
    backgroundColor: colors.darkMuted,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.darkSoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  countBadgeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
    includeFontPadding: false,
  },
  summaryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkMuted,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.darkSoft,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  summaryItem: {
    flex: 1,
    gap: 3,
  },
  summaryDivider: {
    width: 1,
    height: 26,
    backgroundColor: colors.darkSoft,
    marginHorizontal: 12,
  },
  summaryLabel: {
    color: colors.textTertiary,
    fontSize: 12,
    fontWeight: '700',
    includeFontPadding: false,
  },
  summaryValue: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    includeFontPadding: false,
  },
  rankList: {
    gap: 10,
  },
  rankCard: {
    backgroundColor: colors.darkMuted,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.darkSoft,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  myCard: {
    borderColor: colors.indigoAccent,
    backgroundColor: colors.navyCard,
  },
  rankRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rankBadge: {
    minWidth: 52,
    borderRadius: 999,
    backgroundColor: colors.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  rankBadgeText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '800',
    includeFontPadding: false,
  },
  runnerMeta: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  runnerName: {
    color: colors.white,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '800',
    includeFontPadding: false,
  },
  selfBadge: {
    backgroundColor: colors.brandLighter,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  selfBadgeText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: '800',
    includeFontPadding: false,
  },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.successInk,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  livePillDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: colors.successBright,
  },
  livePillText: {
    color: colors.successSoft,
    fontSize: 11,
    fontWeight: '800',
    includeFontPadding: false,
  },
  metricInline: {
    width: 72,
    alignItems: 'flex-end',
  },
  metricInlineValue: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '800',
    includeFontPadding: false,
  },
});
